### ISSUE TITLE
OpenGL Shaders are Broken in Bundled Levels

### ISSUE THREAD

**Issue by coatlessali** [eternalUnion/AngryLevelLoader#1]
Not sure whose bug this is. When running the game with `-force-glcore` to get around hardware/software limitations, a lot of shaders are completely broken, such as:

- "Enraged"
- Checkpoints
- Explosions
- Dust/Wind

![20230709_18h31m50s_grim](https://github.com/eternalUnion/AngryLevelLoader/assets/61166135/dc2376ad-3358-4066-b688-1ebf1730c01b)
![20230709_18h49m47s_grim](https://github.com/eternalUnion/AngryLevelLoader/assets/61166135/31cdac53-13db-474f-9c8a-8200bf071469)

Screenshots are Linux, but I also confirmed it to happen on Windows with a fresh install of BepInEx, PluginConfigurator, and AngryLevelLoader.

**Comment by eternalUnion** [comment]
Found a starting point: `[Error  : Unity Log] Desired shader compiler platform 15 is not available in shader blob`
It might be related to how asset bundles are built
Specifically target graphic API

**Comment by coatlessali** [comment]
![guide-1](https://github.com/eternalUnion/AngryLevelLoader/assets/61166135/a46b3e2d-6b8b-42c8-b365-12048ed1cb89)
I made this little guide a while ago for UNIX compatibility, but it may still apply. This fixed mods such as WafflesWeapons as well.

**Comment by eternalUnion** [comment]
> ![guide-1](https://user-images.githubusercontent.com/61166135/252413928-a46b3e2d-6b8b-42c8-b365-12048ed1cb89.png) I made this little guide a while ago for UNIX compatibility, but it may still apply. This fixed mods such as WafflesWeapons as well.

I already use path methods but I will try building bundles with the second method. If it works, it means the problem is on the rude side

**Comment by eternalUnion** [comment]
It is indeed related to rude side and the second method worked. I will release a new version with the included levels built with the correct build method

**Comment by coatlessali** [comment]
Thanks for the consideration for us OpenGL players. Any ETA on when we could see these fixes pushed?

**Comment by eternalUnion** [comment]
> Thanks for the consideration for us OpenGL players. Any ETA on when we could see these fixes pushed?

New builds on discord should be supported. I am having issues getting the correctly built bundles since I did not build them and also I want to make a quick update which will decrease bundle sizes before pushing. Sorry for the delay, please contact hola and horror on discord if you want to get the correct versions of the bundles at the moment

**Comment by eternalUnion** [comment]
1.0.2 contains doilus map which is open gl friendly. Couldn't get the world series from hola because he had trouble exporting it. On discord, maps should be configurable if authors installed the latest update for rude

**Comment by eternalUnion** [comment]
This issue should be solved, due to addressable shader linking and newly built levels being built with correct shader variants

**Comment by coatlessali** [comment]
Forgot to come back and report results. Working on Windows, MacOS, and Linux.
