### ISSUE TITLE
Angry Level Loader simply not appearing

### ISSUE THREAD

**Issue by benlabcrimson** [eternalUnion/AngryLevelLoader#14]
# Description
So I woke up to the level loader completely gone, I have installed it both manually and with r2modman, but neither seem to detect it. After installation, the "Custom Levels" Button disappeared from the screen and the plugin configuration options imply do not show up AngryLevelLoader

I uninstalled Ultrakill, r2modman, and both at the same time even

It's getting me quite worried because this doesn't happen with any other mod, this is only happening with this mod and i'm not sure why. The level folders for the mod look alright, I haven't compared them to anyone's but it looks like it should work. If there's any questions or info about my installation and such then i'm more than available to give out necessary details

# Plugins Used
* PluginConfigurator (1.8.4)
* AngryLevelLoader (2.7.6)
* Bepinex ofc (5.4.2100)

**Comment by eternalUnion** [comment]
Could you send your console logs?

**Comment by benlabcrimson** [comment]
Sure thing! Although I don't know where they're located. I haven't found a way to access them, do you know in which directory are they in?

**Comment by eternalUnion** [comment]
In bepinex folder, it is named LogOutput.log

**Comment by benlabcrimson** [comment]
[LogOutput.log](https://github.com/eternalUnion/AngryLevelLoader/files/14498634/LogOutput.log)

I think this is it

**Comment by eternalUnion** [comment]
It seems unity logs are not recorded in this file. Open `BepInEx/config/BepInEx.cfg`, change this line to true and open the game again.

```
[Logging.Disk]

## Include unity log messages in log file output.
# Setting type: Boolean
# Default value: false
WriteUnityLog = true
```

**Comment by benlabcrimson** [comment]
[LogOutput.log](https://github.com/eternalUnion/AngryLevelLoader/files/14498847/LogOutput.log)

Got it! Should be on now, not sure what the difference is but I hope this did something

**Comment by eternalUnion** [comment]
Could you check if these files exist in `E:/SteamLibrary/steamapps/common/ULTRAKILL/ULTRAKILL_Data/StreamingAssets/aa/StandaloneWindows64`?

other_assets_allaudio.bundle
other_assets_dooraudio.bundle
other_assets_goreaudio.bundle
other_assets_musicaudio.bundle
other_assets_unfreezeableaudio.bundle

**Comment by benlabcrimson** [comment]
They do, but they're like, a LOT smaller than the other files, so it looks a bit suspicious. The other files say they're from 600 kb to 20 mb, and from other_assets_allaudio.bundle to other_assets_unfreezeableaudio.bundle they're all 3 kb

https://drive.google.com/drive/folders/1xcuKonB0anquU187FU8Qjya4RGadRUoV?usp=sharing

**Comment by eternalUnion** [comment]
I analyzed the files you uploaded. They do not match with the ones from angry and are probably corrupted. Try deleting (or safely moving them away) them so that angry can regenerate them.

**Comment by benlabcrimson** [comment]
It worked! Thank you! They've been regenerated and now it shows up

I wonder how you knew that those files in specific were different... Can't thank you enough!

**Comment by eternalUnion** [comment]
I passed them trough a program that compares files. But I should investigate the origin of the corruption later.

**Comment by benlabcrimson** [comment]
My pc has been corrupting a bunch of files in general, i'm sure it's nothing on your end! Thank you so much man! I seriously can't thank you enough

**Comment by Ksanf1** [comment]
i need help. i tried this but this is not worked

> I analyzed the files you uploaded. They do not match with the ones from angry and are probably corrupted. Try deleting (or safely moving them away) them so that angry can regenerate them.
