### ISSUE TITLE
validation error

### ISSUE THREAD

**Issue by foxipro1675** [eternalUnion/AngryLevelLoader#15]
i want to download a level an it says validation error and it dont download. why this happen?

**Comment by eternalUnion** [comment]
Levels are hosted on google drive. When too many people attempt to download, the file is rate limited and cannot be downloaded until one day or so.

**Comment by eternalUnion** [comment]
Update: It seems some of the older levels are hosted on discord. And discord no longer allows files to be downloaded this way. Levels with such problems will be moved to google drive later on.
