### ISSUE TITLE
[BUG] downloaded Levels do not show as downloaded and do not load at all

### ISSUE THREAD

**Issue by ryboy111** [eternalUnion/AngryLevelLoader#2]
# Description
Title describes it, nothing loads. Even when i put a .angry level in the level folder, it shows up, but with no levels inside.

# Plugins Used
* PluginConfigurator (1.6.0)
* AngryLevelLoader (2.1.0)
* StyleEditor (1.0.1)
* UMM (0.5.6)

**Comment by eternalUnion** [comment]
I used the exact same versions, and was unable to reproduce the issue. Are you using any UMM mods?

**Comment by ryboy111** [comment]
yes, quite a few. however, it turned out that my internet is just horrible. im very sorry for the mistake.
