### ISSUE TITLE
[BUG] "Could not download catalog version" - Network Error

### ISSUE THREAD

**Issue by novaeon** [eternalUnion/AngryLevelLoader#20]
# Description
The online level catalog fails to load and stays blank, no matter how long I wait. The error in the console pops up immideatly after clicking refresh, which implies that it's not an issue of the connection timing out or slow internet.
![image](https://github.com/eternalUnion/AngryLevelLoader/assets/75177537/30f70acc-db5d-4667-b62c-4fdf18370b48)

# Plugins Used
* PluginConfigurator (1.9.0)
* AngryLevelLoader (2.9.0)

# Console Logs
If you have any errors or warnings on the bepinex console, log below. (How to open the console: https://docs.bepinex.dev/articles/user_guide/troubleshooting.html)
![image](https://github.com/eternalUnion/AngryLevelLoader/assets/75177537/5f7f50a4-f25c-4b44-bdbf-d4340687f9e0)

**Comment by eternalUnion** [comment]
It may be a problem related to your system. Try switching to a different network or changing firewall settings.

**Comment by tungstengmd** [comment]
this is with me too

**Comment by eternalUnion** [comment]
Then could you try opening this link on your browser? https://raw.githubusercontent.com/eternalUnion/AngryLevels/release/LevelCatalog.json last time someone couldn't even access it from there

**Comment by tungstengmd** [comment]
where do we place this?

**Comment by tungstengmd** [comment]
fixed magically
