### ISSUE TITLE
[BUG] Angry Level Loader always stuck on a single difficulty

### ISSUE THREAD

**Issue by PaulGuyNitro1** [eternalUnion/AngryLevelLoader#24]
# Description
even though i might be playing in Brutal, its like if i was playing in Violent.

# Plugins Used
* PluginConfigurator (v1.10.0)
* AngryLevelLoader (v2.10.0)
* (other used mods if present)

# Console Logs
nothing i have been able to find about it

# Extras
none

**Comment by eternalUnion** [comment]
Duplicate
