### ISSUE TITLE
[BUG] Level votes not showing

### ISSUE THREAD

**Issue by Mahonzu** [eternalUnion/AngryLevelLoader#26]
# Description
Level ratings (votes) are not showing
![image](https://github.com/user-attachments/assets/41a9c2bb-0ca5-403b-aa5e-876711572127)

# Plugins Used
* PluginConfigurator (1.10.0)
* AngryLevelLoader (2.10.0)

# Console Logs
```
[Info   :AngryLevelLoader] Cached script catalog up to date
[Info   :AngryLevelLoader] Current online level catalog is up to date, loading from cache
[Error  :AngryLevelLoader] Could not get all votes while refreshing. Message: . Status: FAILED.
```

# Extras
This is not the same as #21 I tried diefferent proton versions, reloging into steam, restarting steam, rebooting, and even fresh install only with Level loader and Plugin configurator

**Comment by eternalUnion** [comment]
It is not a bug. Angry server is currently down and will be reopened on August 29-30.
