### ISSUE TITLE
[BUG] Angry Mod Loader doesn't load

### ISSUE THREAD

**Issue by DamageMaximo** [eternalUnion/AngryLevelLoader#28]
# Description
I install Angry Mod Loader through R2modman along with the dependency but it seems the mod doesn't load, none of the buttons that allow access to the level list appear, as if the mod isn't installed, I grabbed the same files from when I played modded ULTRAKILL in my hard drive, where I had angry mod loader and it used to work and I just put it there to see if it works in the SSD and still, it's as if the mod doesn't exist 
![image](https://github.com/user-attachments/assets/1bc7d921-a72c-4b22-865d-b37776b02790)
![image](https://github.com/user-attachments/assets/8b1ab38c-31a0-4692-aaa2-50a703add864)
![image](https://github.com/user-attachments/assets/d31bf99f-b5e9-4ded-8b29-73c4316a5d07)

# Plugins Used
* PluginConfigurator (1.10.0)
* AngryLevelLoader (2.10.0)
* BepInExPack v5.4.2100

# Console Logs
If you have any errors or warnings on the bepinex console, log below. (How to open the console: https://docs.bepinex.dev/articles/user_guide/troubleshooting.html)
```
[Error  : Unity Log] UnauthorizedAccessException: Access to the path "C:\Users\DAAIP" is denied.
Stack trace:
System.IO.Directory.CreateDirectoriesInternal (System.String path) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.IO.Directory.CreateDirectory (System.String path) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.IO.DirectoryInfo.Create () (at <44afb4564e9347cf99a1865351ea8f4a>:0)
(wrapper remoting-invoke-with-check) System.IO.DirectoryInfo.Create()
System.IO.Directory.CreateDirectoriesInternal (System.String path) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.IO.Directory.CreateDirectory (System.String path) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.IO.DirectoryInfo.Create () (at <44afb4564e9347cf99a1865351ea8f4a>:0)
(wrapper remoting-invoke-with-check) System.IO.DirectoryInfo.Create()
System.IO.Directory.CreateDirectoriesInternal (System.String path) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.IO.Directory.CreateDirectory (System.String path) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.IO.DirectoryInfo.Create () (at <44afb4564e9347cf99a1865351ea8f4a>:0)
(wrapper remoting-invoke-with-check) System.IO.DirectoryInfo.Create()
System.IO.Directory.CreateDirectoriesInternal (System.String path) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.IO.Directory.CreateDirectory (System.String path) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
AngryLevelLoader.IOUtils.TryCreateDirectory (System.String path) (at <5aff509bab384847a253ec1ce7c9d112>:0)
AngryLevelLoader.Plugin.PostAwake () (at <5aff509bab384847a253ec1ce7c9d112>:0)
AngryLevelLoader.Plugin.Awake () (at <5aff509bab384847a253ec1ce7c9d112>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.InputSystem.InputSystem:.cctor()
```

# Extras
It says that access to a path is denied at the top, but there's nothing of the game in there, that name is my hard drive, and ULTRAKILL, Steam, R2modman, and it's folders including the mods are on the SSD under a different name, and on the settings on R2Modman it says all the folders being accessed are on the correct path, but when I boot up the game it says that error on the console, I have no idea why that is happening. Maybe there is an easy fix for this but I'm not aware of it.
![image](https://github.com/user-attachments/assets/8e34e4c0-62f0-4e71-89a2-414321960ae5)
![image](https://github.com/user-attachments/assets/91033e8b-8ecf-4445-b0ba-26b8a664ba05)

**Comment by eternalUnion** [comment]
There is a hidden config file which stores the path where .angry files are searched for. I assume it is somehow set to the user directory so angry cannot access it. You could try moving this file to somewhere else so that it is recreated and the path is defaulted to '%appdata%/AngryLevelLoader'. The file you should move away should be in 'ULTRAKILL/BepInEx/config/PluginConfigurator/eternalUnion.AngryLevelLoader.internalConfig' (last part may be different but must end with internal config. move the folder to a safe place and try again).

**Comment by DamageMaximo** [comment]
It worked, thank you! 
![image](https://github.com/user-attachments/assets/572d7651-65a1-470c-bb79-dae21bb0f6d3)
