### ISSUE TITLE
[BUG] AGONY does not download at all

### ISSUE THREAD

**Issue by winterviola** [eternalUnion/AngryLevelLoader#4]
# Description
Not sure if this should be put here or in the AngryLevels repository, but AGONY doesn't download when trying to download it from the in-game catalog. The progress bar appears for a second saying  `0 / 181.9 MB` and then disappears and the level doesn't show up in the menu. The BepInEx console doesn't output anything after pressing it, either.

Looking at LevelCatalog.json manually and opening the download URL associated with the level gives a 404/403 page, so it's presumably invalid.

# Plugins Used
* PluginConfigurator (1.6.0)
* AngryLevelLoader (2.3.1, also happens on 2.3.0)

**Comment by eternalUnion** [comment]
It is not an angry related issue. It seems that dropbox has a bandwith limit of 20 GB. When it got exceeded by multiple people downloading via angry, dropbox automatically rate limited the file. Then it probably got deleted by luka. [Here is the page prior to the removal of the file](https://cdn.discordapp.com/attachments/1133473397276426280/1148941758386933811/image.png)

Our plan is to switch to shared google drive files

**Comment by eternalUnion** [comment]
We are switching between file host services for now. Slow downloads or levels not being available may occur in the future until we find a reliable host.
