### ISSUE TITLE
[BUG] Specific levels not downloading (ones with a big file size)

### ISSUE THREAD

**Issue by User67541** [eternalUnion/AngryLevelLoader#5]
I tried downloading "THE CHEB MUSEUM" and "AGONY (BETA)", for a while it was going good but then the download randomly stopped (not at the file size), it didnt display installed and the levels had a white image but in the level selection the levels are there (even when pressing open on the level) but i fear the file might be corrupted or something, or a display error.

**//After opening the levels (that had a white photos at frist) they showed up (like normal), it worked but the visual display confused me, hopefully doesnt happen again** 

_-no error/warnings in the console_

**--Plugins--**
* PluginConfigurator (1.6.0)
* AngryLevelLoader (2.3.3)
* UltrakillStyleEditor (1.0.1)
* UltraPain (1.1.0)
* UMM (5.6.0)
* Jacket (0.7.20)
* UKsoundReplacement (1.2.6)

**Comment by eternalUnion** [comment]
could you send me the file, it should be in `%appdata%/AngryLevelLoader/Levels`

**Comment by eternalUnion** [comment]
I should also mention that I am self hosting those levels and downloads will be pretty slow, especially with multiple users downloading at the same time

**Comment by User67541** [comment]
> could you send me the file, it should be in `%appdata%/AngryLevelLoader/Levels`

i cant send them here, and the levels are not corrupted but i guess the download part of it was bugged

**Comment by User67541** [comment]
> I should also mention that I am self hosting those levels and downloads will be pretty slow, especially with multiple users downloading at the same time

that's resonable but sometimes when downloading something big it just stops

**Comment by ATStaley** [comment]
I have virtually the same problem, most levels only download for half a second, then just stop :(

**Comment by eternalUnion** [comment]
We are still having problems with file hosting

**Comment by eternalUnion** [comment]
Switched to parted file system, may help with the current situation
