### ISSUE TITLE
[BUG] Levels divided into parts are not downloading

### ISSUE THREAD

**Issue by Ardub92** [eternalUnion/AngryLevelLoader#6]
# Description
When I try to download one of the levels that are divided into parts they simply can not download. I can spend hours clicking levels that are divided into parts, but It will not download the level, but I can easily go to your repository and download levels from there. But after this version that split levels into parts I now can't just put the level in Levels folder, and I have no idea how I unzip the level parts. I cleaned everything before the mod and other mods, but no succeed.

# Plugins Used
* PluginConfigurator (2.4.0)
* AngryLevelLoader (1.6.0)

**Comment by eternalUnion** [comment]
Any console errors? And which level?

**Comment by Ardub92** [comment]
> Any console errors? And which level?

Almost all of them, no errors.
BTW, I want to point out, even the small levels some are not downloading.

**Comment by eternalUnion** [comment]
Could you export the preset from plugin configurator and send it trough here?

**Comment by Ardub92** [comment]
> Could you export the preset from plugin configurator and send it trough here?

Here, this file will be deleted in hour: https://tmpfiles.org/dl/2660074/pluginconfigurator.zip

**Comment by eternalUnion** [comment]
Not sure about the cause. If you can download from a browser, it should be able to download from angry. Maybe it could be a systematic issue like a firewall.

**Comment by Ardub92** [comment]
Sorry, it's my bad and not Firewall issue
