### ISSUE TITLE
[FEATURE] Jaket mod support

### ISSUE THREAD

**Issue by JustWantAName06** [eternalUnion/AngryLevelLoader#7]
# Description
Although it is *kinda* possible to use jaket mod in tandem with it its still kinda buggy. The enemies don't load for both players and some triggers are kinda buggy

# Usage
Allows players to do angry levels together and hopefully allow the creation of pvp maps (PLEASE THIS WOULD BE SO SO SO COOL!!!)

# Extras
I love this mod, nothing else to say

**Comment by eternalUnion** [comment]
I think this should be requested in jacket. Don't know how much I can do about it on angry side alone
